name       : python-pyscard
version    : 2.0.0
release    : 7
source     :
    - https://github.com/LudovicRousseau/pyscard/archive/2.0.0.tar.gz : 314d44a46d14c25c532c4679c116991ae720d62bce3739e82a9b2a34acd86b18
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Smartcard module for Python
description: |
    pyscard - python smart card library - is a python module adding smart cards support to python.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(python3)
    - swig
rundeps    :
    - pcsc-lite
setup      : |
    %python3_setup
install    : |
    %python3_install
