name       : python-pyscard
version    : 1.9.8
release    : 5
source     :
    - https://github.com/LudovicRousseau/pyscard/archive/release-1.9.8.tar.gz : 1ba887b5cef1eaab4d270563888bf48f6be3a48787687c3a85a6ac8767779802
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Smartcard module for Python
description: |
    pyscard - python smart card library - is a python module adding smart cards support to python.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(python3)
    - swig
rundeps    :
    - pcsc-lite
setup      : |
    %python3_setup
install    : |
    %python3_install
