name       : python-pyscard
version    : 1.9.4
release    : 1
source     :
    - https://pypi.python.org/packages/a0/59/05e00160d4a386502b60bfcc7591e0443561306b9ca1954bca841692014a/pyscard-1.9.4.tar.gz : 9b4c36b98264a1ec6523561cb904724b16022d6ba051b5d14b69c2862eb9c03e
license    : LGPL-2.0
component  : programming.python
summary    : Smartcard module for Python.
description: |
    Smartcard module for Python.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(python-3.5)
    - python-setuptools
    - swig
rundeps    :
    - pcsc-lite
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
