name       : python-pyscard
version    : 1.9.7
release    : 4
source     :
    - https://github.com/LudovicRousseau/pyscard/archive/release-1.9.7.tar.gz : 402956d4c2c0ae265ff5d590efdf80297b07060fa923230658e682cff29a27a2
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Smartcard module for Python.
description: |
    Smartcard module for Python.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(python3)
    - python-setuptools
    - swig
rundeps    :
    - pcsc-lite
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
